### ISSUE TITLE
SaveConfig is always true

### ISSUE THREAD

**Issue by almereyda** [githubixx/ansible-role-wireguard#136]
Even when setting `wireguard_save_config: "false"` explicitly on each host or for the group, all of their configurations will have `SaveConfig = true` present.

**Comment by githubixx** [comment]
Just remove the variable `wireguard_save_config`. Currently the implementation only checks if `wireguard_save_config` is present and if so adds `SaveConfig = true`. Otherwise the setting won't be set. ATM the implementation doesn't care about the variable value. I guess this is something I should change.
