### ISSUE TITLE
Install requires specific version 

### ISSUE THREAD

**Issue by ieugen** [githubixx/ansible-role-wireguard#15]
Hi, 

Ansible galaxy complains, fails to find version. 

You need to specify the exact version `ansible-galaxy install githubixx.ansible_role_wireguard,3.2.0`

```
 gr8pi-production git:(gr8pi-prod) ✗ ansible-galaxy install githubixx.ansible_role_wireguard      
- downloading role 'ansible_role_wireguard', owned by githubixx
 [WARNING]: - githubixx.ansible_role_wireguard was NOT installed successfully: Unable to compare role versions (2.0.1, 3.0.0, 3.0.1, 3.1.0, 3.2.0,
v1.0.2, v1.0.1, 2.0.0, v1.0.0) to determine the most recent version due to incompatible version formats. Please contact the role author to resolve
versioning conflicts, or specify an explicit role version to install.

```

**Comment by githubixx** [comment]
Thx for reporting the issue! This happens because Ansible Galaxy refactored their versioning support the past months which is quite annoying as old Git tags not following their supported version scheme needs to be deleted to make it work and possibly breaking peoples installations :disappointed: But doesn't help... I removed all tags starting with `v` now and its working now as expected for me.
