### ISSUE TITLE
`wireguard_cert_owner` demands local root access - is that necessary?

### ISSUE THREAD

**Issue by ieugen** [githubixx/ansible-role-wireguard#16]
Hi, 

Using your role as a non root leads to 
```
TASK [githubixx.ansible_role_wireguard : Create WireGuard certificates directory] ***********************************************************************************************
fatal: [master-0.k8s.gr8pi.org -> localhost]: FAILED! => {"changed": false, "gid": 1000, "group": "ieugen", "mode": "0755", "msg": "chown failed: [Errno 1] Operation not permitted: b'/home/user/production/ansible/wireguard-certs'", "owner": "user", "path": "/home/user/production/ansible/wireguard-certs", "size": 4096, "state": "directory", "uid": 1000}
```
Is the permission change necessary to be done locally ?  If not I think it might make the role much portable.

```
wireguard_cert_owner: "root"
wireguard_cert_group: "root"
```

**Comment by githubixx** [comment]
:wave: Well I also don't really like it but haven't had any time to figure out if it could be implemented differently.

If I assume all users would just use a directory in their `$HOME` directory it won't be needed. But what happens if you want to use `/etc/wireguard/` e.g.? Only `root` has access to `/etc` by default and therefore only `root` is able to create a directory `/etc/wireguard`. Of course I can state I don't care and the user is responsible that he's able/have the permissions to create a directory within whatever parent directory and just fail if that is not possible.

The general idea behind this was that the certificates may end up in a NFS/Samba share so that it can be used by other people in the IT department, team, and so on. And in this case it makes sense to set the owner/group accordingly (which reminds me to also make the directory mode bits configurable but that's a different thing :wink: ).

**Comment by ieugen** [comment]
I see, we ended up rolling our own ansible role for wireguard.

We generate the keys on each node and we slurp them and then generate the file by template. 

Seems a better approach for us and avoids nuiscenses like the above.

**Comment by githubixx** [comment]
What ever works for you :wink: Then I guess we can close this issue.
