### ISSUE TITLE
No peers when limiting hosts

### ISSUE THREAD

**Issue by sebix** [githubixx/ansible-role-wireguard#180]
No peers are being added to the configuration file if `ansible-playbook` is used with `--limit` to only run the script only on a part of the network.
The reason is the usage for `ansible_play_hosts`:
https://github.com/githubixx/ansible-role-wireguard/blob/f6a6e4680a6061622bee2351daadaa30f60f953d/templates/etc/wireguard/wg.conf.j2#L47

`ansible_play_hosts` gets limited when using the `--limit` parameter.

Is there a way to get a correct configuration file when limiting the destination hosts?

**Comment by githubixx** [comment]
I know that `ansible_play_hosts` is a problem. That happens when you accept a PR and don't oversee the consequences :wink: That's something that should be changed or at least another possibility added that could get around this. But currently I belief that's it not that easy. If you only change a limited set of hosts you most probably still need the facts from the other hosts. I've something in mind but I don't know when I'll have time. But pull requests are welcome of course :wink:

**Comment by githubixx** [comment]
This is already covered in https://github.com/githubixx/ansible-role-wireguard/issues/79. So I'll close this one.
