### ISSUE TITLE
NAT / keepalive logic

### ISSUE THREAD

**Issue by Madic-** [githubixx/ansible-role-wireguard#36]
At the moment, according to the example in the readme, the wireguard endpoint behind a NAT should have keepalive configured. This configures keepalives from all hosts to the host behind NAT. But shouldn't it be the other way around? The NATed endpoint needs to send keepalives to the other endpoints to be reachable.
The problem is, if the NATed endpoint doesn't send any frame over wireguard, the tunnel never comes up because the other endpoints can't send keepalives to the endpoint behind the nat. That's problematic if an endpoint, or a network, behind the nat should be accessible.

I think either the logic needs to be the other way around or maybe a ping from the device behind the nat to the other endpoints added to the role could help to initialize the tunnel.

Or do I miss something?

**Comment by githubixx** [comment]
TBH I don't really understand your question. You can set `wireguard_persistent_keepalive` for every host you like. Just set it in `host_vars/` directory (or wherever it fits best for you) for what ever host you like. The example works for me. But it's just an example. For which host you set `wireguard_persistent_keepalive` is up to you.

**Comment by Madic-** [comment]
No problem. I try another approach :)

At the moment, if configuring `wireguard_persistent_keepalive` for an endpoint, all endpoints are configured to send keepalives to the endpoint which has `wireguard_persistent_keepalive` configured. That's a problem if this endpoint is behind a nat and no data has been send from this endpoint to the other endpoints because the tunnel isn't yet up.

```
endpoint1: on the internet, sends keepalives to endpoint2
endpoint2: behind nat, with wireguard_persistent_keepalive configured
                     NAT
endpoint1 --->--->--->|--->--->endpoint2
```
This only works if endpoint2 has already send data to endpoint1 over wireguard. So needs a manual ping or some other kind of manual connection after configuring wireguard.

Better would be the other way around.
```
endpoint1: on the internet
endpoint2: behind nat, sends keepalives to host1
                     NAT
endpoint1 <---<---<---|<---<---endpoint2
```
Of course I can configure `wireguard_persistent_keepalive` for every host which endpoint2 should have access to. But that would also configure keepalives between every other endpoints.

**Comment by githubixx** [comment]
This makes it more clear to me - at least I hope so :wink: . Thanks for clarification! Well, I basically agree with you that the current implementation is not perfect in this regards ATM. But if I configure `wireguard_persistent_keepalive` then this only means that the `PersistentKeepalive` configuration will show up in every Wireguard configuration that has a connection to that host.

This is basically true for my home server. It's behind a NAT gateway and therefore I've configured `wireguard_persistent_keepalive` for this host. ATM this means that the `PersistentKeepalive` setting also appears in all my other Wireguard configuration files for this host as I've a fully meshed network where every host can communicate with the other. So you're basically right that it would be sufficient if only my home server would have `PersistentKeepalive` set for all hosts it wants to communicate with but not the other way round.

But on the other hand I forward Wiregard traffic on port `51820` from the internet to my internal Wireguard host anyways. So Wireguard keep alives should arrive at the Wireguard interface at my internal host. If there is no such forwarding then probes from the internet to the host behind the NAT gateway won't arrive at first. 

Well, that's maybe something that should be addressed but I don't see this as a critical issue ATM. Having a few extra keep alives packets flowing around doesn't seem to be a big issue IMHO.  I haven't thought of a possible solution yet (maybe a simple configuration option is already enough) but due to time constraints I think can't address this issue in the near future.

**Comment by Madic-** [comment]
I thought a bit about it but the time to investigate isn't realy worth the effort.

What I came up with was some kind of workaround, to bring the tunnel up with this role:
Doing pings from the endpoint having `wireguard_persistent_keepalive` configured to all the other endpoints. But that's something I wouldn't implement in my roles because it feels more of a workaround.

So thank you for your detailed response :) From my point of view this issue can be closed
