### ISSUE TITLE
 Variables to set server public/private key

### ISSUE THREAD

**Issue by j8r** [githubixx/ansible-role-wireguard#65]
Maybe it cannot be considered as a best practice, but when having a lots of clients already configured, it is very impractical to bother everyone to change their configuration when we re-deploy our WireGuard instance.

ansible-vault is used, and the private key is occasionally rotated. Doing this tasks can be recommended in the documentation.

**Comment by githubixx** [comment]
TBH I'm not totally sure what you're trying to tell me :wink: ATM this role is mainly about managing servers. If there are hosts that are occasionally disconnected e.g. and can't be managed or updated when you deploy the role, this role can't update the configuration of that hosts/clients of course.

If I get you right then you need kind of a pull mechanism for the public key of the WireGuard server in question. E.g. a cronjob that fetches the public key from somewhere (maybe via sftp from whatever server) and checks if the public key has changed and if so the script replaces the public key in `wg0.conf` and runs `wg syncconf wg0 <(wg-quick strip /etc/wireguard/wg0.conf)` afterwards.

I hope this helps.

**Comment by j8r** [comment]
@githubixx We are using WireGuard as a classic VPN, like VPN providers does with OpenVPN since a long time.
I change the title to be more clear, I was talking about the server private, and eventually public key. If it changes, all client need to change their configuration too.

I can make a PR to have this optional variables:
```yaml
wireguard_private_key = ...
wireguard_public_key = ...
``` 

I preferred to open an issue before doing so.

**Comment by j8r** [comment]
As a side note, I'm using currently the fork from the PR https://github.com/githubixx/ansible-role-wireguard/pull/63 to manage all the users (thank you to @joneskoo ).

**Comment by githubixx** [comment]
So if I get you right your issue would be solved if #63 will be merged, right? I just did a review of that one with a few comments that should be addressed before merging.

**Comment by j8r** [comment]
No @githubixx , that's only part of the use-case.
No worry, I'll make a PR, will be quite simple.

The goal is to avoid avoid to create a new key (`wg genkey`), and take the one from a variable.

**Comment by ypid** [comment]
I am also interested in this issue. As mentioned in #66, there is an Ansible role (https://docs.debops.org/en/master/ansible/roles/tinc/index.html) goes into this direction.

I now had more time to think about this. I also noticed the design @githubixx choose that he pointed out in https://github.com/githubixx/ansible-role-wireguard/pull/58#issuecomment-668866994. I find it clever to avoid the redundancy in `/etc/wireguard` by only having the keys there instead of duplicating them in separate private/public key files. Also it is interesting to only having the private key on the host that actually needs them.

But, as @j8r has pointed out, this brings limitations. So I would at least propose a second mode where private keys are generated/stored on the Ansible controller and distributed from there. I would use this design for my own use case exclusively for now. I see the Ansible controller as being ultimately trusted. If you don’t trust it to hold all your private keys, it is already game over. That is not to say that the design from @githubixx cannot help here when people don’t have such requirements.

My use case is that I like to clean install Debian VMs instead of doing inplace upgrades. WireGuard VPN servers are an ideal candidate for automated reinstalls as they hold very little state. But I don’t want to update all my clients when I do.

Me as a DebOps developer, I would go with the https://docs.debops.org/en/master/ansible/roles/secret/index.html role but I guess ansible-vault is more generic.

One thing I would like to mention in general that applies to #69 is that I want Ansible to actually save me work. I want to  provide as little information as necessary and Ansible does the rest. Why do I manually need to run some wg command when I use Ansible?

**Comment by j8r** [comment]
@ypid You don't necessarily "have to" run the command locally. Using a variable is very simple and flexible. For example, the secret can be generate din some way automatically and regularly by whatever tool, and stored in a place like Amazon Secret Manager, then do a `{{ lookup('aws_secret', ... }}`.

I think that what you propose can be too complicated to be in this role's scope.

**Comment by ypid** [comment]
I know the lookup plugins, but I also know that none of them easily supports to fully automate this. But I understand that my proposal might be too complicated. I would then instead suggest to state that automating this is the overall goal or add such a script directly.

**Comment by ypid** [comment]
Cc: @fbourqui, @pierreozoux
Ref: #29, #23, #18

As you guys basically removed Ansible controller managed private keys :) I am not saying that this is bad, but there are legitimate use cases for doing it from the controller. So:

> I would at least propose a second mode where private keys are generated/stored on the Ansible controller and distributed from there.

**Comment by ypid** [comment]
I switched to this "mode" now in https://github.com/ypid/ansible-wireguard/tree/prepare-for-debops. The idea is that it is configurable via `wireguard__secret_authority` but I have not tested the host only mode so I might have broken it. At least the PSK deployment currently only works with the Ansible controller.
