### ISSUE TITLE
Combined effort with DebOps?

### ISSUE THREAD

**Issue by ypid** [githubixx/ansible-role-wireguard#66]
Hey there, DebOps developer here. I found your role to be the best starting point to add WireGuard support to DebOps and would like to have your feedback on it.

For now, I see these viable options:

1. Make the role itself auto detect (Ansible local facts) when it runs against a DebOps managed host and behave in a compatibly way. Additionally, as DebOps is a comprehensive approach to configuration management, I would need to maintain a wrapper role in DebOps that manages the Firewall. An example how this can look like is DebOps’s tor relay role: https://github.com/debops/debops/tree/master/ansible/roles/tor and its corresponding playbook:
https://github.com/debops/debops/blob/master/ansible/debops-contrib-playbooks/service/tor.yml This is an intermidiate option but it would avoid the forking that I don’t like.

2. **Fork the role and make it a native DebOps role following https://docs.debops.org/en/master/dep/dep-0002.html**

   Edit: That is kinda unavoidable. I started this work at https://github.com/ypid/ansible-wireguard/tree/prepare-for-debops

3. We update the role and move it to DebOps :)

This is not urgent for me. I will open a improvement PR and a second one to add DebOps compatibility following option 1 and then you can have a look at the code.

Also note that DebOps has a role which solves similar problems of setting up a distributed public key system, https://docs.debops.org/en/master/ansible/roles/tinc/index.html. I will look into this older role again to compare your design with this one. Note that the tinc role has not be reworked since 2017 so it is not the most up-to-date one. There are more high-quality once if you want to check one out.

**Comment by githubixx** [comment]
Thanks for your input and PR. Lets start the at the easy end :wink: After having a quick view on your draft PR https://github.com/githubixx/ansible-role-wireguard/pull/67 I think it's ok if it stays that way. Namespaces are ok for me. I've no problem with that kind of change.

In general this role was created to only serve one purpose and that was to enable secure communication of Kubernetes resources of my K8s cluster. I published it on Github for people who want to follow my little K8s installation blog series or have a similar need. I tried to make it as general as possible so that it can be used for other purposes too. But somewhere I need to draw I line because I can't maintain every use case. This is also the point where I tell people to fork the role. I've really no problem with that. That's how OpenSource works now and then, right? :wink:

That being said https://github.com/githubixx/ansible-role-wireguard/pull/67 in its current form looks mergable to me and is useful in general. But if I need really need to implement or maintain external dependencies or something like that e.g. then I'm out. That goes beyond for what I created this role and I simply don't have the time to take care about such things. In this case as already mentioned a fork is perfectly ok for me.

**Comment by ypid** [comment]
Thanks for your detailed answer! Sounds good to me. Nice that you made the role open and kudos for making it general. I think you did a good job with that.

So I will try to do option one for now. My requirements are not too high currently. So I will work together with you while keeping the option to fork and integrate natively into DebOps in the back of my mind. I am interested to get your role more feature complete first. Things like #58 and #63 are interesting to me and I will look into them.

**Comment by githubixx** [comment]
Keeping an eye on #63 makes sense. This is a long requested feature and the implementation should be good enough for most users IHMO. So I guess I'll merge that one first if my comments are addressed.

**Comment by githubixx** [comment]
I guess we can close this one. IMHO we discussed most things here and in other tickets.

**Comment by ypid** [comment]
So Long, and Thanks for All the Fish.
