### ISSUE TITLE
Exact license used (SPDX license indentifier): GPL-3.0-only or GPL-3.0-or-later?

### ISSUE THREAD

**Issue by ypid** [githubixx/ansible-role-wireguard#72]
Which license do you mean exactly by "GNU GENERAL PUBLIC LICENSE Version 3" ? Is it [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html)?

**Comment by githubixx** [comment]
No idea what `-or-later` means :wink: There is nothing like that at https://www.gnu.org/licenses/. When I create a new repository at Github you can add a license and I choose always `GNU General Public License v3.0` (also see https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository). But they're all release on 29 June 2007 . I'm not a license expert and personally I don't care. The important thing for me is that software released as open source should stay open source. That's why I normally don't choose a BSD license.

**Comment by ypid** [comment]
Default GPL license text is `-or-later` meaning that when a new version of the GPL gets released, users can apply it to your project without you having to review/approve this first. `-only` does not.

SPDX license identifier are the definitive way to identify licenses, also backed by the Linux Foundation.
https://www.linuxfoundation.org/blog/2018/08/solving-license-compliance-at-the-source-adding-spdx-license-ids/

This distinction is also important for #71.

**Comment by githubixx** [comment]
In that case the `-or-later` option makes most sense to me. I guess FSF has good enough lawyers to not introduce crap in future versions of this license.
